version: '3.1'

services:
  auth_db:
    container_name: auth_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
      POSTGRES_DB: auth      
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    networks:
      - auth_network      

  dbgate:
    image: dbgate/dbgate
    restart: always
    depends_on:
      - auth_db
    ports:
      - 8080:3000
    environment:
      CONNECTIONS: con1
      LABEL_con1: Postgres
      SERVER_con1: auth_db
      USER_con1: user
      PASSWORD_con1: 123
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres      
    networks:
      - auth_network    

networks:
  auth_network:
    driver: bridge

volumes:
  auth_db_data: {}